### ISSUE TITLE
add a way to start from any path ID

### ISSUE THREAD

**Issue by nikita-skobov** [nikita-skobov/collabopath#10]
otherwise users will have to re-trace their steps in the tree every single time!

This presents an issue though: when starting from any path ID, should they still allocate stats and such?

**Comment by drdreo** [comment]
For debug purposes this can help out. 
But isn't the purpose of the game to end up in a different path every time. Giving a new player the option to start where they want kind of reduces the experience. 
Probably a savepoint could work. A player can find or create a savepoint, he then can decide if he wants to restart from the beginning or a savepoint. Would limit this to the session. So you can only create and reload savepoints when you have at least been there once.

**Comment by nikita-skobov** [comment]
I'll definitely work on a save system, that's a good idea. if the branches ever get so long, it might not be possible to traverse all the way down a branch in one go, so a user might want to come back to it later.

As for the starting anywhere the user wants: I think this game should be about exploring, and if you need to start from the beginning every time, it might be really annoying to the user to have to experience the same paths over and over. Also, what if somebody makes a really interesting story way out at path ID 9999 or something... nobody will want to click through a hundred buttons just to see that users story.

**Comment by nikita-skobov** [comment]
feature is now part of master. but as of 11/28 is not part of the live website. I'll add some more features and make a new release sometime this weekend.

This feature works by:
- adding a new button where users can specify a specific path ID
- adding a special case path viewer stage. (previously stage 0 was "What is your name?", now it is "Which path would you like to start at?")
- adding logic to download both the users requested path, AND the path before it.

I messed up with the merge, so if you see some weird commits with something about revert feature/start-any-path I apologize.
